name: Java Pull Request Check

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "packages/java/**"

  pull_request:
    branches: [main]
    paths:
      - "packages/java/**"

  workflow_dispatch:

jobs:
  checking-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        working-directory: ./packages/java
        run: mvn dependency:resolve

      - name: Run Tests
        working-directory: ./packages/java
        run: mvn test

      - name: Build Project
        working-directory: ./packages/java
        run: mvn -B package

      - name: Check if target directory is created
        run: |
          if [ ! -d "./packages/java/target" ]; then
            echo "target directory is not created"
            exit 1
          fi
          echo "Build successful, target directory exists."
